# Generated by Django 4.1.6 on 2023-02-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vid',
            old_name='year',
            new_name='release',
        ),
    ]
